{
 "title": "Pizza Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Total Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pizza_revenue{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Creations",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pizza_failures{source=\"jwt-pizza-service\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "CPU/Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu{source=\"jwt-pizza-service\"}",
     "legendFormat": "cpu"
    },
    {
     "expr": "system_memory{source=\"jwt-pizza-service\"}",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "latency_creation{source=\"jwt-pizza-service\"}",
     "legendFormat": "creation"
    },
    {
     "expr": "latency_endpoint{source=\"jwt-pizza-service\"}",
     "legendFormat": "endpoint"
    }
   ]
  },
  {
   "title": "Sales",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "pizza_sold{source=\"jwt-pizza-service\"}",
     "legendFormat": "sold"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "activeUsers_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "total_users"
    }
   ]
  },
  {
   "title": "Auth Attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "authAttempts_success{source=\"jwt-pizza-service\"}",
     "legendFormat": "success"
    },
    {
     "expr": "authAttempts_failure{source=\"jwt-pizza-service\"}",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "requests_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "total"
    },
    {
     "expr": "requests_GET{source=\"jwt-pizza-service\"}",
     "legendFormat": "get"
    },
    {
     "expr": "requests_PUT{source=\"jwt-pizza-service\"}",
     "legendFormat": "put"
    },
    {
     "expr": "requests_POST{source=\"jwt-pizza-service\"}",
     "legendFormat": "post"
    },
    {
     "expr": "requests_DELETE{source=\"jwt-pizza-service\"}",
     "legendFormat": "delete"
    }
   ]
  }
 ]
}